/* Generated by the CMS build. Edit data.json through the admin, not here. */
window.WORKS = [
  {
    "id": 1,
    "title": "Kyma Coffee Roasters",
    "category": "Branding",
    "img": "img/branding-1.png",
    "href": "https://www.behance.net/rgbil",
    "alt": "Kyma Coffee Roasters — branding",
    "avif": "img/opt/branding-1-480.avif 480w, img/opt/branding-1-768.avif 768w, img/opt/branding-1-1080.avif 1080w",
    "webp": "img/opt/branding-1-480.webp 480w, img/opt/branding-1-768.webp 768w, img/opt/branding-1-1080.webp 1080w",
    "w": 1414,
    "h": 2000
  },
  {
    "id": 2,
    "title": "Meraki Studio",
    "category": "Branding",
    "img": "img/branding-4.png",
    "href": "https://www.behance.net/rgbil",
    "alt": "Meraki Studio — branding",
    "avif": "img/opt/branding-4-480.avif 480w, img/opt/branding-4-768.avif 768w, img/opt/branding-4-1080.avif 1080w",
    "webp": "img/opt/branding-4-480.webp 480w, img/opt/branding-4-768.webp 768w, img/opt/branding-4-1080.webp 1080w",
    "w": 1414,
    "h": 2000
  },
  {
    "id": 3,
    "title": "Elaia Olive Oil",
    "category": "Packaging",
    "img": "img/packaging-1.png",
    "href": "https://www.behance.net/rgbil",
    "alt": "Elaia Olive Oil — packaging",
    "avif": "img/opt/packaging-1-480.avif 480w, img/opt/packaging-1-768.avif 768w, img/opt/packaging-1-1080.avif 1080w",
    "webp": "img/opt/packaging-1-480.webp 480w, img/opt/packaging-1-768.webp 768w, img/opt/packaging-1-1080.webp 1080w",
    "w": 1414,
    "h": 2000
  },
  {
    "id": 4,
    "title": "Anthos Botanicals",
    "category": "Packaging",
    "img": "img/packaging-5.png",
    "href": "https://www.behance.net/rgbil",
    "alt": "Anthos Botanicals — packaging",
    "avif": "img/opt/packaging-5-480.avif 480w, img/opt/packaging-5-768.avif 768w, img/opt/packaging-5-1080.avif 1080w",
    "webp": "img/opt/packaging-5-480.webp 480w, img/opt/packaging-5-768.webp 768w, img/opt/packaging-5-1080.webp 1080w",
    "w": 1414,
    "h": 2000
  },
  {
    "id": 5,
    "title": "Nocturne Editions",
    "category": "Covers & Posters",
    "img": "img/covers-1.png",
    "href": "https://www.behance.net/rgbil",
    "alt": "Nocturne Editions — covers & posters",
    "avif": "img/opt/covers-1-480.avif 480w, img/opt/covers-1-768.avif 768w, img/opt/covers-1-1080.avif 1080w",
    "webp": "img/opt/covers-1-480.webp 480w, img/opt/covers-1-768.webp 768w, img/opt/covers-1-1080.webp 1080w",
    "w": 1414,
    "h": 2000
  },
  {
    "id": 6,
    "title": "Athens Type Week",
    "category": "Covers & Posters",
    "img": "img/covers-5.png",
    "href": "https://www.behance.net/rgbil",
    "alt": "Athens Type Week — covers & posters",
    "avif": "img/opt/covers-5-480.avif 480w, img/opt/covers-5-768.avif 768w, img/opt/covers-5-1080.avif 1080w",
    "webp": "img/opt/covers-5-480.webp 480w, img/opt/covers-5-768.webp 768w, img/opt/covers-5-1080.webp 1080w",
    "w": 1414,
    "h": 2000
  }
];
