/* Generated by the CMS build. Edit data.json through the admin, not here. */
window.WORKS = [
  {
    "id": 1,
    "title": "Project 01",
    "category": "Branding",
    "img": "img/work-1.png",
    "href": "https://www.behance.net/rgbil",
    "avif": "img/opt/work-1-480.avif 480w, img/opt/work-1-768.avif 768w, img/opt/work-1-1080.avif 1080w",
    "webp": "img/opt/work-1-480.webp 480w, img/opt/work-1-768.webp 768w, img/opt/work-1-1080.webp 1080w",
    "w": 1200,
    "h": 900
  },
  {
    "id": 2,
    "title": "Project 02",
    "category": "Packaging",
    "img": "img/work-2.png",
    "href": "https://www.behance.net/rgbil",
    "avif": "img/opt/work-2-480.avif 480w, img/opt/work-2-768.avif 768w, img/opt/work-2-1080.avif 1080w",
    "webp": "img/opt/work-2-480.webp 480w, img/opt/work-2-768.webp 768w, img/opt/work-2-1080.webp 1080w",
    "w": 1200,
    "h": 900
  },
  {
    "id": 3,
    "title": "Project 03",
    "category": "Covers & Posters",
    "img": "img/work-3.png",
    "href": "https://www.behance.net/rgbil",
    "avif": "img/opt/work-3-480.avif 480w, img/opt/work-3-768.avif 768w, img/opt/work-3-1080.avif 1080w",
    "webp": "img/opt/work-3-480.webp 480w, img/opt/work-3-768.webp 768w, img/opt/work-3-1080.webp 1080w",
    "w": 1200,
    "h": 900
  },
  {
    "id": 4,
    "title": "Project 04",
    "category": "Branding",
    "img": "img/work-4.png",
    "href": "https://www.behance.net/rgbil",
    "avif": "img/opt/work-4-480.avif 480w, img/opt/work-4-768.avif 768w, img/opt/work-4-1080.avif 1080w",
    "webp": "img/opt/work-4-480.webp 480w, img/opt/work-4-768.webp 768w, img/opt/work-4-1080.webp 1080w",
    "w": 1200,
    "h": 900
  },
  {
    "id": 5,
    "title": "Project 05",
    "category": "Packaging",
    "img": "img/work-5.png",
    "href": "https://www.behance.net/rgbil",
    "avif": "img/opt/work-5-480.avif 480w, img/opt/work-5-768.avif 768w, img/opt/work-5-1080.avif 1080w",
    "webp": "img/opt/work-5-480.webp 480w, img/opt/work-5-768.webp 768w, img/opt/work-5-1080.webp 1080w",
    "w": 1200,
    "h": 900
  },
  {
    "id": 6,
    "title": "Project 06",
    "category": "Covers & Posters",
    "img": "img/work-6.png",
    "href": "https://www.behance.net/rgbil",
    "avif": "img/opt/work-6-480.avif 480w, img/opt/work-6-768.avif 768w, img/opt/work-6-1080.avif 1080w",
    "webp": "img/opt/work-6-480.webp 480w, img/opt/work-6-768.webp 768w, img/opt/work-6-1080.webp 1080w",
    "w": 1200,
    "h": 900
  }
];
